### ISSUE TITLE
wrong time settings

### ISSUE THREAD

**Issue by theojurriens** [mireianievas/PySQM#2]
was testing your software , looks good but looks like there is a evening
![SQM_GRONINGEN](https://user-images.githubusercontent.com/54167998/63849219-e91ddc80-c991-11e9-8873-90237028ae91.png)
twilight issue in the graph: offset with 1 hour?

Location Groningen, the Netherlands

**Comment by mireianievas** [comment]
Might have to do with summer time, it always makes a bit of a mess with small tools, particularly if you want to support both windows and linux.

**Comment by theojurriens** [comment]
i had a config.py in two different directories with different timezone :-( now i corrected to utc + 1, will see what happens...

**Comment by theojurriens** [comment]
something else: i use rclone to copy files after night run
