### ISSUE TITLE
correct axis label "mag/arcsec²" instead of "mag/arcsec2"

### ISSUE THREAD

**Issue by Tartouffe** [mireianievas/PySQM#6]
Hello, 

to be displayed "mag/arcsec2" at the axis label correctly "mag/arcsec²" with the superscript ^2
can please anyone change the sourcecode in file "pysqm/plot.py" at

- Line 456
  self.thegraph_sunalt.set_ylabel('Sky Brightness (mag/arcsec2)',fontsize='medium')
  to
  self.thegraph_sunalt.set_ylabel('Sky Brightness (mag/arcsec$\mathregular{^2}$)',fontsize='medium')

- Line 499
  self.thegraph_time.set_ylabel('Sky Brightness (mag/arcsec2)',fontsize='medium')
  to
  self.thegraph_time.set_ylabel('Sky Brightness (mag/arcsec$\mathregular{^2}$)',fontsize='medium')

The command  $\mathregular{^2}$  does a real superscript without any font change (e.g. can happen when you use an alternate character like »²« or some unicode).

Result will looks like:
![upl](https://user-images.githubusercontent.com/86598230/155282170-20bcf97d-bad8-4d8e-93ef-a20cc03d0987.png)

**Comment by mireianievas** [comment]
Feel free to open a pull request next time :)
